[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
methods = { path = "../methods" }
risc0-zkvm = { version = "0.21.0" }
serde = "1.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
