[package]
name = "verifier-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
risc0-zkvm = { version = "0.21.0", default-features = false }
methods = { path = "../methods" }
risc0-zkp = "0.21.0"

